# Data reading and pre-cleaning

In [10]:
import pandas as pd

In [11]:
original_data = pd.read_excel('../data/original/original_data.xlsx', sheet_name='Sheet1')

print (original_data.head())

         ID PtGender PtAge                                      Diagnosis  \
0  23765692        男   68岁         消化道穿孔腹膜炎冠状动脉粥样硬化性心脏病高血压脑梗死冠状动脉粥样硬化性心脏病
1  23765694        男   89岁                                 乏力低钾血症贫血低钾血症贫血
2  23765695        男   77岁  药物中毒高血压陈旧性心肌梗死冠状动脉粥样硬化性心脏病恶性肿瘤个人史陈旧性心肌梗死前列腺增生
3  23765696        女   91岁     昏迷糖尿病伴有酮症酸中毒型糖尿病急性脑血管病阿尔茨海默病型糖尿病肾功能不全肝功能不全
4  23765697        女   34岁                                             发热

   FYZ-IgM   甲流   乙流  分组汇总    WBC   RBC  ...  MONO%  EO%  BASO%   IG#  IG%  \
0      NaN  NaN  NaN   NaN   9.70  4.92  ...    3.4  0.0    0.0  0.01  0.1
1      NaN  2.0  NaN   2.0   8.69  3.11  ...    3.9  6.0    0.2  0.07  0.8
2      NaN  NaN  NaN   NaN  11.04  4.33  ...    5.4  4.5    0.3  0.01  0.1
3      NaN  NaN  NaN   NaN  10.44  2.77  ...    0.5  0.3    0.0  0.09  0.9
4      NaN  NaN  3.0   3.0   3.00  4.29  ...   11.8  1.0    0.3  0.00  0.0

     CRP  HFLC1  HFLC2  NRBC#  NRBC%
0  94.34   0.03    0.3    0.0    0.0
1    NaN   0.01    0.2    0.0    0.0
2    NaN   0.01    0.1    0.0    0.0
3    NaN   0.01    0.1    0.0    0.0
4   0.95   0.00    0.1    0.0    0.0

[5 rows x 39 columns]

### Pre-cleaning

In [12]:
original_data['PtAge'] = original_data['PtAge'].astype(str)

# 处理 '岁'
original_data.loc[original_data['PtAge'].str.contains('岁', na=False), 'PtAge'] = original_data.loc[original_data['PtAge'].str.contains('岁', na=False), 'PtAge'].str.replace('岁', '').astype(float)

# 处理 '天'
original_data.loc[original_data['PtAge'].str.contains('天', na=False), 'PtAge'] = original_data.loc[original_data['PtAge'].str.contains('天', na=False), 'PtAge'].str.replace('天', '').astype(float) / 365

# 处理 '月'
original_data.loc[original_data['PtAge'].str.contains('月', na=False), 'PtAge'] = original_data.loc[original_data['PtAge'].str.contains('月', na=False), 'PtAge'].str.replace('月', '').astype(float) / 12

# 将转换后的年龄转换为浮点数
original_data['PtAge'] = original_data['PtAge'].astype(float)

# change 男女 to 0, 1
original_data['PtGender'] = original_data['PtGender'].replace({'男': 0, '女': 1})
original_data.drop_duplicates(inplace=True)
# for data in diagnosis, keep the rows with '发烧‘ only, 
# for data in 分组汇总, only keep those with empty and make a new dataframe
not_infected_data = original_data[original_data['Diagnosis'] == '发热']
not_infected_data = not_infected_data[not_infected_data['分组汇总'].isnull()]
# positive data is those not in the not_infected_data
positive_data = original_data[original_data['分组汇总'].notnull()]
positive_data

,ID,PtGender,PtAge,Diagnosis,FYZ-IgM,甲流,乙流,分组汇总,WBC,RBC,...,MONO%,EO%,BASO%,IG#,IG%,CRP,HFLC1,HFLC2,NRBC#,NRBC%
1,23765694,0.0,89.0,乏力低钾血症贫血低钾血症贫血,NaN,2.0,NaN,2.0,8.69,3.11,...,3.9,6.0,0.2,0.07,0.8,NaN,0.01,0.2,0.0,0.0
4,23765697,1.0,34.0,发热,NaN,NaN,3.0,3.0,3.00,4.29,...,11.8,1.0,0.3,0.00,0.0,0.95,0.00,0.1,0.0,0.0
45,23769968,1.0,23.0,呼吸困难,1.0,NaN,NaN,1.0,21.35,4.30,...,5.1,0.6,0.1,0.02,0.1,41.00,0.01,0.0,0.0,0.0
67,23773946,1.0,17.0,咳嗽,1.0,NaN,NaN,1.0,11.48,3.99,...,4.9,0.3,0.3,0.00,0.0,35.00,0.00,0.0,0.0,0.0
86,23774757,1.0,12.0,急性扁桃体炎,1.0,NaN,NaN,1.0,6.28,4.77,...,10.1,0.1,0.0,0.00,0.0,21.91,0.02,0.3,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20919,24026660,0.0,29.0,发热,NaN,2.0,NaN,2.0,4.82,5.47,...,12.2,0.2,0.2,0.00,0.0,11.63,0.00,0.0,NaN,NaN
20924,24027023,0.0,20.0,发热,1.0,NaN,NaN,1.0,8.70,5.01,...,12.1,5.5,0.7,0.02,0.2,30.17,0.03,0.3,NaN,NaN
20926,24027047,1.0,18.0,发热,NaN,2.0,NaN,2.0,5.13,4.33,...,16.4,0.0,0.4,0.00,0.0,3.60,0.00,0.0,NaN,NaN
20927,24027055,1.0,21.0,发热,NaN,2.0,NaN,2.0,4.17,4.83,...,20.1,0.0,0.5,0.01,0.2,5.82,0.01,0.2,NaN,NaN
20928,24027090,0.0,19.0,发热,NaN,2.0,NaN,2.0,9.84,5.10,...,8.0,0.1,0.1,0.01,0.1,13.26,0.02,0.2,NaN,NaN

In [13]:
original_data.describe()

,ID,PtGender,PtAge,FYZ-IgM,甲流,乙流,分组汇总,WBC,RBC,HGB,...,MONO%,EO%,BASO%,IG#,IG%,CRP,HFLC1,HFLC2,NRBC#,NRBC%
count,2.093100e+04,20915.000000,20901.000000,2255.0,2698.0,180.0,4794.000000,20931.000000,20931.000000,20931.000000,...,20920.000000,20930.000000,20931.000000,20929.000000,20929.000000,18638.000000,20917.000000,20917.000000,17588.000000,17588.000000
mean,2.391222e+07,0.527660,32.335900,1.0,2.0,3.0,2.345015,8.528668,4.487609,132.726960,...,8.157357,1.301056,0.215680,0.034958,0.336156,16.923381,0.026673,0.347712,0.002542,0.025228
std,7.091205e+04,0.499246,23.559567,0.0,0.0,0.0,2.733956,5.412591,0.707574,21.775053,...,3.604326,1.824411,0.208438,0.160750,0.923051,28.547930,0.070412,0.716571,0.043192,0.415907
min,2.376551e+07,0.000000,0.000000,1.0,2.0,3.0,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.385850e+07,0.000000,14.000000,1.0,2.0,3.0,1.000000,5.930000,4.210000,124.000000,...,5.600000,0.200000,0.100000,0.010000,0.100000,2.390000,0.010000,0.100000,0.000000,0.000000
50%,2.392192e+07,1.000000,26.000000,1.0,2.0,3.0,2.000000,7.700000,4.570000,135.000000,...,7.500000,0.700000,0.200000,0.010000,0.200000,7.785000,0.010000,0.200000,0.000000,0.000000
75%,2.397281e+07,1.000000,46.000000,1.0,2.0,3.0,2.000000,10.075000,4.920000,146.000000,...,10.100000,1.700000,0.300000,0.030000,0.300000,19.030000,0.030000,0.400000,0.000000,0.000000
max,2.402725e+07,1.000000,99.000000,1.0,2.0,3.0,13.000000,466.400000,7.350000,242.000000,...,53.700000,49.400000,6.000000,9.880000,28.600000,362.370000,6.350000,42.400000,3.092000,33.230000

In [14]:
# print summary of data
print(original_data.info())
print(original_data.describe())
print(not_infected_data.info())
print(not_infected_data.describe())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20931 entries, 0 to 20930
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         20931 non-null  int64
 1   PtGender   20915 non-null  float64
 2   PtAge      20901 non-null  float64
 3   Diagnosis  20768 non-null  object
 4   FYZ-IgM    2255 non-null   float64
 5   甲流         2698 non-null   float64
 6   乙流         180 non-null    float64
 7   分组汇总       4794 non-null   float64
 8   WBC        20931 non-null  float64
 9   RBC        20931 non-null  float64
 10  HGB        20931 non-null  int64
 11  HCT        20931 non-null  float64
 12  MCV        20931 non-null  float64
 13  MCH        20931 non-null  float64
 14  MCHC       20931 non-null  int64
 15  PLT        20931 non-null  int64
 16  RDW-SD     20931 non-null  float64
 17  RDW-CV     20931 non-null  float64
 18  PDW        20916 non-null  float64
 19  MPV        20916 non-null  float64
 20  P-LCR      20916 non-null  float64
 21  PCT        20916 non-null  float64
 22  NEUT       20929 non-null  float64
 23  LY         20920 non-null  float64
 24  MONO       20920 non-null  float64
 25  EO         20930 non-null  float64
 26  BASO       20931 non-null  float64
 27  NEUT%      20929 non-null  float64
 28  LYBL%      20920 non-null  float64
 29  MONO%      20920 non-null  float64
 30  EO%        20930 non-null  float64
 31  BASO%      20931 non-null  float64
 32  IG#        20929 non-null  float64
 33  IG%        20929 non-null  float64
 34  CRP        18638 non-null  float64
 35  HFLC1      20917 non-null  float64
 36  HFLC2      20917 non-null  float64
 37  NRBC#      17588 non-null  float64
 38  NRBC%      17588 non-null  float64
dtypes: float64(34), int64(4), object(1)
memory usage: 6.4+ MB
None
                 ID      PtGender         PtAge  FYZ-IgM      甲流     乙流  \
count  2.093100e+04  20915.000000  20901.000000   2255.0  2698.0  180.0
mean   2.391222e+07      0.527660     32.335900      1.0     2.0    3.0
std    7.091205e+04      0.499246     23.559567      0.0     0.0    0.0
min    2.376551e+07      0.000000      0.000000      1.0     2.0    3.0
25%    2.385850e+07      0.000000     14.000000      1.0     2.0    3.0
50%    2.392192e+07      1.000000     26.000000      1.0     2.0    3.0
75%    2.397281e+07      1.000000     46.000000      1.0     2.0    3.0
max    2.402725e+07      1.000000     99.000000      1.0     2.0    3.0

              分组汇总           WBC           RBC           HGB  ...  \
count  4794.000000  20931.000000  20931.000000  20931.000000  ...
mean      2.345015      8.528668      4.487609    132.726960  ...
std       2.733956      5.412591      0.707574     21.775053  ...
min       1.000000      0.000000      0.000000      0.000000  ...
25%       1.000000      5.930000      4.210000    124.000000  ...
50%       2.000000      7.700000      4.570000    135.000000  ...
75%       2.000000     10.075000      4.920000    146.000000  ...
max      13.000000    466.400000      7.350000    242.000000  ...

              MONO%           EO%         BASO%           IG#           IG%  \
count  20920.000000  20930.000000  20931.000000  20929.000000  20929.000000
mean       8.157357      1.301056      0.215680      0.034958      0.336156
std        3.604326      1.824411      0.208438      0.160750      0.923051
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        5.600000      0.200000      0.100000      0.010000      0.100000
50%        7.500000      0.700000      0.200000      0.010000      0.200000
75%       10.100000      1.700000      0.300000      0.030000      0.300000
max       53.700000     49.400000      6.000000      9.880000     28.600000

                CRP         HFLC1         HFLC2         NRBC#         NRBC%
count  18638.000000  20917.000000  20917.000000  17588.000000  17588.000000
mean      16.923381      0.026673      0.347712      0.002542      0.025228
std       28.547930      0.070412      0.716571      0.043192      0.415907
min        0.000000      0.000000      0.000000      0.000000      0.000000
25%        2.390000      0.010000      0.100000      0.000000      0.000000
50%        7.785000      0.010000      0.200000      0.000000      0.000000
75%       19.030000      0.030000      0.400000      0.000000      0.000000
max      362.370000      6.350000     42.400000      3.092000     33.230000

[8 rows x 38 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 3178 entries, 70 to 20929
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         3178 non-null   int64
 1   PtGender   3178 non-null   float64
 2   PtAge      3178 non-null   float64
 3   Diagnosis  3178 non-null   object
 4   FYZ-IgM    0 non-null      float64
 5   甲流         0 non-null      float64
 6   乙流         0 non-null      float64
 7   分组汇总       0 non-null      float64
 8   WBC        3178 non-null   float64
 9   RBC        3178 non-null   float64
 10  HGB        3178 non-null   int64
 11  HCT        3178 non-null   float64
 12  MCV        3178 non-null   float64
 13  MCH        3178 non-null   float64
 14  MCHC       3178 non-null   int64
 15  PLT        3178 non-null   int64
 16  RDW-SD     3178 non-null   float64
 17  RDW-CV     3178 non-null   float64
 18  PDW        3177 non-null   float64
 19  MPV        3177 non-null   float64
 20  P-LCR      3177 non-null   float64
 21  PCT        3177 non-null   float64
 22  NEUT       3178 non-null   float64
 23  LY         3178 non-null   float64
 24  MONO       3178 non-null   float64
 25  EO         3178 non-null   float64
 26  BASO       3178 non-null   float64
 27  NEUT%      3178 non-null   float64
 28  LYBL%      3178 non-null   float64
 29  MONO%      3178 non-null   float64
 30  EO%        3178 non-null   float64
 31  BASO%      3178 non-null   float64
 32  IG#        3178 non-null   float64
 33  IG%        3178 non-null   float64
 34  CRP        3174 non-null   float64
 35  HFLC1      3178 non-null   float64
 36  HFLC2      3178 non-null   float64
 37  NRBC#      2167 non-null   float64
 38  NRBC%      2167 non-null   float64
dtypes: float64(34), int64(4), object(1)
memory usage: 993.1+ KB
None
                 ID     PtGender        PtAge  FYZ-IgM   甲流   乙流  分组汇总  \
count  3.178000e+03  3178.000000  3178.000000      0.0  0.0  0.0   0.0
mean   2.392294e+07     0.549087    31.855412      NaN  NaN  NaN   NaN
std    6.595412e+04     0.497663    15.855296      NaN  NaN  NaN   NaN
min    2.376558e+07     0.000000     0.333333      NaN  NaN  NaN   NaN
25%    2.387553e+07     0.000000    20.000000      NaN  NaN  NaN   NaN
50%    2.392795e+07     1.000000    28.000000      NaN  NaN  NaN   NaN
75%    2.397357e+07     1.000000    38.000000      NaN  NaN  NaN   NaN
max    2.402722e+07     1.000000    97.000000      NaN  NaN  NaN   NaN

               WBC          RBC          HGB  ...        MONO%          EO%  \
count  3178.000000  3178.000000  3178.000000  ...  3178.000000  3178.000000
mean      7.916649     4.675183   139.879484  ...     9.409157     0.860856
std       3.460582     0.515769    16.279941  ...     3.693028     1.165601
min       0.410000     2.280000    52.000000  ...     0.300000     0.000000
25%       5.560000     4.320000   130.000000  ...     6.700000     0.200000
50%       7.240000     4.660000   139.000000  ...     8.900000     0.400000
75%       9.420000     5.020000   152.000000  ...    11.500000     1.100000
max      32.080000     6.980000   202.000000  ...    30.900000    13.500000

             BASO%          IG#          IG%          CRP        HFLC1  \
count  3178.000000  3178.000000  3178.000000  3174.000000  3178.000000
mean      0.252203     0.022882     0.256923    21.267224     0.014119
std       0.198189     0.057395     0.394450    27.131959     0.019794
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       0.100000     0.010000     0.100000     5.405000     0.000000
50%       0.200000     0.010000     0.200000    12.160000     0.010000
75%       0.300000     0.030000     0.300000    26.522500     0.020000
max       3.900000     2.230000     9.900000   287.540000     0.290000

             HFLC2        NRBC#        NRBC%
count  3178.000000  2167.000000  2167.000000
mean      0.208181     0.000189     0.003341
std       0.339623     0.002897     0.061082
min       0.000000     0.000000     0.000000
25%       0.100000     0.000000     0.000000
50%       0.100000     0.000000     0.000000
75%       0.200000     0.000000     0.000000
max       9.000000     0.080000     2.170000

[8 rows x 38 columns]

In [15]:
columns_to_drop = ['Diagnosis', 'FYZ-IgM', '甲流', '乙流', '分组汇总']
not_infected_data.drop(columns = columns_to_drop)

,ID,PtGender,PtAge,WBC,RBC,HGB,HCT,MCV,MCH,MCHC,...,MONO%,EO%,BASO%,IG#,IG%,CRP,HFLC1,HFLC2,NRBC#,NRBC%
70,23774029,0.0,79.0,6.84,4.34,145,42.3,97.5,33.4,343,...,7.3,1.6,0.0,0.01,0.1,25.78,0.00,0.1,0.0,0.0
99,23774788,1.0,61.0,3.31,4.37,135,40.0,91.5,30.9,338,...,8.4,0.0,0.2,0.00,0.1,14.10,0.09,2.7,0.0,0.0
115,23774873,1.0,21.0,8.01,4.42,122,37.5,84.8,27.6,325,...,9.4,0.1,0.1,0.01,0.1,17.12,0.01,0.1,0.0,0.0
116,23774874,1.0,25.0,4.02,4.89,141,42.6,87.1,28.8,331,...,12.6,0.4,0.1,0.00,0.1,1.18,0.03,0.7,0.0,0.0
121,23774888,1.0,35.0,16.30,3.97,122,36.5,91.9,30.9,334,...,4.3,2.3,0.2,0.03,0.2,31.46,0.04,0.2,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20921,24026827,0.0,23.0,5.52,5.05,150,45.5,90.1,29.7,330,...,13.9,0.2,0.2,0.01,0.2,4.42,0.01,0.2,NaN,NaN
20922,24026921,1.0,29.0,6.83,4.02,121,35.2,87.6,30.1,344,...,9.7,0.7,0.3,0.02,0.3,6.48,0.00,0.0,NaN,NaN
20923,24026931,0.0,29.0,5.59,5.12,149,44.8,87.5,29.1,333,...,14.3,6.8,0.2,0.04,0.7,12.50,0.01,0.2,NaN,NaN
20925,24027035,0.0,34.0,6.06,4.91,148,46.0,93.7,30.1,322,...,16.5,0.2,0.3,0.01,0.2,1.60,0.01,0.2,NaN,NaN
20929,24027216,0.0,24.0,6.67,4.97,148,42.4,85.3,29.8,349,...,15.0,1.8,0.4,0.01,0.1,2.70,0.01,0.1,NaN,NaN

In [16]:
print(positive_data.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4794 entries, 1 to 20928
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         4794 non-null   int64
 1   PtGender   4793 non-null   float64
 2   PtAge      4793 non-null   float64
 3   Diagnosis  4768 non-null   object
 4   FYZ-IgM    2255 non-null   float64
 5   甲流         2698 non-null   float64
 6   乙流         180 non-null    float64
 7   分组汇总       4794 non-null   float64
 8   WBC        4794 non-null   float64
 9   RBC        4794 non-null   float64
 10  HGB        4794 non-null   int64
 11  HCT        4794 non-null   float64
 12  MCV        4794 non-null   float64
 13  MCH        4794 non-null   float64
 14  MCHC       4794 non-null   int64
 15  PLT        4794 non-null   int64
 16  RDW-SD     4794 non-null   float64
 17  RDW-CV     4794 non-null   float64
 18  PDW        4794 non-null   float64
 19  MPV        4794 non-null   float64
 20  P-LCR      4794 non-null   float64
 21  PCT        4794 non-null   float64
 22  NEUT       4794 non-null   float64
 23  LY         4792 non-null   float64
 24  MONO       4792 non-null   float64
 25  EO         4794 non-null   float64
 26  BASO       4794 non-null   float64
 27  NEUT%      4794 non-null   float64
 28  LYBL%      4792 non-null   float64
 29  MONO%      4792 non-null   float64
 30  EO%        4794 non-null   float64
 31  BASO%      4794 non-null   float64
 32  IG#        4794 non-null   float64
 33  IG%        4794 non-null   float64
 34  CRP        4726 non-null   float64
 35  HFLC1      4790 non-null   float64
 36  HFLC2      4790 non-null   float64
 37  NRBC#      3072 non-null   float64
 38  NRBC%      3072 non-null   float64
dtypes: float64(34), int64(4), object(1)
memory usage: 1.5+ MB
None

In [17]:
# combine positive and not_infected data
combined_data = pd.concat([positive_data, not_infected_data])

In [18]:
combined_data.to_csv('../data/curated/combined_data.csv', index=False)